version: '3'
services:
  backend:
    build: ./backend/
    ports:
     - "5000:5000"
    volumes:
     - ./backend:/app
  frontend:
    build: ./frontend/
    ports:
     - "3000:3000"
    volumes:
     - ./frontend:/app
     - /app/node_modules
  db:
    image: "mongo:latest"
    volumes:
     - ./db:/data/db
